name: Tag Release on Push

on:
  push:
    branches:
      - release

jobs:
  tag-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Tag Release
        uses: "s-bridges/tag-release-on-push-action@v1.0.2"
        with:
          tag_prefix: "v"
          release_name: "Release ${{ github.sha }}"
          release_body: "Release ${{ github.sha }}"
