name: Add Release Tag

on:
  push:
    branches:
      - release

jobs:
  add-release-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Release Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ github.sha }} -m "Release ${{ github.sha }}"
          git push origin v${{ github.sha }}
